# RocketMQ Broker 配置
# 宿主机 Windows 上跑 Spring Boot 时，客户端从 NameServer 拿到的 Broker 地址必须是 127.0.0.1
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
brokerIP1 = 127.0.0.1
listenPort = 10911
autoCreateTopicEnable = true
